version = 1

# Uncomment this line once you have added tests to the project.
# [[analyzers]]
# name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "php"

[[analyzers]]
name = "docker"

[[transformers]]
name = "php-cs-fixer"
