version = 1

# Uncomment these lines once you have added tests to the project.
# [[analyzers]]
# name = "test-coverage"

# Uncomment these lines once you have added SQL code tho the proejct.
# [[analyzers]]
# name = "sql"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "php"

[[analyzers]]
name = "docker"

[[transformers]]
name = "php-cs-fixer"
